variables:
  TARGETARCH: amd64
  TARGETOS: linux
  REGISTRY: ghcr.io
  APP: "bot"
  TELE_TOKEN: $TELE_TOKEN

stages:
  - test
  - build

test:
  stage: test
  image: golang:latest
  script:
    - make test
  only:
    - main

build:
  stage: build
  image: docker:20.10.7-git
  services:
    - docker:dind
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - VERSION=$(git describe --tags)
    - docker build  --platform ${TARGETOS}/${TARGETARCH} . -t ${REGISTRY}/${APP}:${VERSION}-${TARGETOS}-${TARGETARCH}
    - docker push ${REGISTRY}/${APP}:${VERSION}-${TARGETOS}-${TARGETARCH} 
  only:
    - main
