variables:
  TARGETARCH: amd64
  TARGETOS: linux
  REGISTRY: registry.gitlab.com
  APP: "bot"
  CI_TOKEN: $CI_JOB_TOKEN
  TELE_TOKEN: $TELE_TOKEN
  REGISTRY_TOKEN: $REGISTRY_TOKEN
  REGISTRY_USERNAME: $REGISTRY_USERNAME
  FILE_PATH: helm/values.yaml

stages:
  - test
  - build

test:
  stage: test
  image: golang:latest
  script:
    - make test
  only:
    - main

build:
  stage: build
  image: golang:latest
  script:
    - make build
  
  