variables:
  TARGETARCH: amd64
  TARGETOS: linux
  REGISTRY: registry.gitlab.com
  APP: "bot"
  CI_TOKEN: $CI_JOB_TOKEN
  TELE_TOKEN: $TELE_TOKEN
  FILE_PATH: helm/values.yaml

stages:
  - test
  - build
  - img
  - push

test:
  stage: test
  image: golang:latest
  script:
    - make test
  only:
    - main

build:
  stage: build
  image: golang:latest
  script:
    - make build

img:
  stage: img
  image: docker:latest
  script:
    - make image
  
push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - make push