variables:
  TARGETARCH: amd64
  TARGETOS: linux
  APP: "bot"
  TELE_TOKEN: $TELE_TOKEN

stages:
  - test
  - build
  - img
  - push

test:
  stage: test
  image: golang:latest
  script:
    - make test
  only:
    - main

build:
  stage: build
  image: golang:latest
  script:
    - make build

img:
  stage: img
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apt-get update && apt-get install -y make
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - make image
  
push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apt-get update && apt-get install -y make 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - make push