name: BOT-CICD

on: push

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Test
        run: make test 

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOOCKERHUB_USERNAME }}
          password: ${{ secrets.DOOCKERHUB_TOKEN }}
      
      - name: build&Push
        env:
          APP: "bot"
          REGISTRY: ${{ secrets.DOOCKERHUB_USERNAME }}
        run: make image push


    
