name: BOT-CICD

on:
  push:
    branches:
      - 'develop'

env:
  TARGETARCH: amd64
  TARGETOS: linux
  REGISTRY: ghcr.io
  APP: bot
  TELE_TOKEN: ${{ secrets.TELE_TOKEN }}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Test
        run: make test 

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GIT_USER }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Make env
        uses: SpicyPizza/create-envfile@v2.0
        with:
          file_name: .env
          fail_on_empty: false
          sort_keys: false
        # uses: docker/login-action@v2
        # with:
        #   username: ${{ secrets.GIT_USER }}
        #   password: ${{ secrets.GIT_TOKEN }}
          # username: ${{ secrets.DOOCKERHUB_USERNAME }}
          # password: ${{ secrets.DOOCKERHUB_TOKEN }}
      
      - name: Build
        run: cat .env && make image REGISTRY=$REGISTRY/romaonyshkiv

      - name: Push
        run: make push REGISTRY=$REGISTRY/romaonyshkiv

      # - name: build&Push
      #   env:
      #     APP: "bot"
      #     REGISTRY: ${{ secrets.DOOCKERHUB_USERNAME }}
      #   run: make image push

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag=strenv(VERSION) | .image.arch=strenv(TARGETARCH) | .image.os=strenv(TARGETOS) | .image.registry=strenv(REGISTRY)' helm/values.yaml

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "update version $VERSION"
          git push